# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'RxActivityIndicator_Example' do

  use_frameworks!

  pod 'RxActivityIndicator', :path => '../'

end
